# Generated by Django 5.2.17 on 2026-09-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniformItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(choices=[('TSHIRT', 'T-Shirt'), ('TROUSER', 'Trouser'), ('SHORT', 'Short'), ('SWEATER', 'Sweater'), ('INNER', 'Inner'), ('OTHER', 'Other')], max_length=30)),
                ('size', models.CharField(max_length=20)),
                ('current_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADDED', 'Added'), ('REMOVED', 'Removed')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date_received', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.uniformitem')),
            ],
        ),
    ]
