# Generated by Django 6.1.1 on 2026-09-30 08:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10)),
            ],
            options={
                'ordering': ['uniform_type__name', 'size'],
            },
        ),
        migrations.CreateModel(
            name='UniformType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Added'), ('OUT', 'Removed')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('issued_to', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='uniform_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.uniformtype'),
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
        migrations.DeleteModel(
            name='UniformItem',
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('uniform_type', 'size')},
        ),
    ]
