# Generated by Django 6.1.1 on 2026-09-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockitem_uniformtype_stockmovement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniformtype',
            options={'ordering': ['name']},
        ),
    ]
