# Generated by Django 6.1.1 on 2026-09-30 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_uniformtype_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-date', '-id'], 'permissions': [('can_receive_stock', 'Can receive stock'), ('can_issue_stock', 'Can issue stock'), ('can_return_stock', 'Can record returned stock'), ('can_writeoff_stock', 'Can write off lost or damaged stock')]},
        ),
        migrations.AddField(
            model_name='stockitem',
            name='reorder_level',
            field=models.PositiveIntegerField(default=5, help_text='Shown as LOW when the balance is at or below this number.'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='recorded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='issued_to',
            field=models.CharField(blank=True, help_text='Who it was issued to / who returned it.', max_length=150, verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Received'), ('OUT', 'Issued'), ('RETURN', 'Returned'), ('LOSS', 'Written off')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, help_text='Delivery note, reason for write-off, condition of returned items...', max_length=255),
        ),
    ]
